name = "eyg_beam"
version = "0.1.0"
target = "erlang"

description = "Check and run EYG programs from Erlang and Elixir hosts."
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "eyg-lang", path = "packages/eyg_beam", tag_prefix = "eyg_beam-" }
links = [{ title = "Website", href = "https://eyg.run" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
eyg_analysis = { path = "../gleam_analysis" }
eyg_interpreter = { path = "../gleam_interpreter" }
eyg_ir = { path = "../gleam_ir" }
eyg_parser = { path = "../gleam_parser" }
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.7.0 and < 3.0.0"
