name = "counters"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
eyg_beam = { path = "../../packages/eyg_beam" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[erlang]
application_start_module = "counters_app"
