name = "overlay_tui_core"
version = "0.1.0"
target = "javascript"

[dependencies]
plinth = { path = "../plinth" }
gleam_opentui = { path = "../gleam_opentui" }
overlay_terminal = { path = "../overlay_terminal" }
plinthx = { path = "../plinthx" }
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
eyg_cli = { path = "../gleam_cli" }
loam = { path = "../loam" }
filepath = ">= 1.0.0 and < 2.0.0"

[javascript]
runtime = "bun"
typescript_declarations = true

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
